template = "https://github.com/giellalt/template-lang-und"
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
