template = "https://github.com/giellalt/template-lang-und"
rev_id = 331
template_sha = "8cacf2c4546a4e46881bd306e8c347aa8b1ae938"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
