template = "https://github.com/giellalt/template-lang-und"
rev_id = 336
template_sha = "389e4bc166fb75b7405a9d137e775aeee3aae1fb"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
